#!/bin/bash

#PBS -o Progetto2.out
#PBS -e Progetto2.err
#PBS -q studenti
#PBS -l nodes=1:ppn=8
#PBS -N Progetto2

cat $PBS_NODEFILE

PBS_O_WORKDIR=$PBS_O_HOME/Progetto2

echo -----------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH

echo -----------------------------------

export PSC_OMP_AFFINITY=TRUE

gcc -lgomp -fopenmp -lm -o $PBS_O_WORKDIR/Progetto2 $PBS_O_WORKDIR/main.c

$PBS_O_WORKDIR/Progetto2 -1 1 1

echo -----------------------------------